export const localidades = [
    "Chapinero",
    "Candelaria",
    "Teusaquillo",
    "Usaquen",
    "Suba",
    "Fontibon",
    "Kennedy",
    "Engativa",
    "Bosa",
    "San Cristobal",
    "Antonio Nariño",
    "Ciudad Bolivar",
    "Tunjuelito",
    "Barrios Unidos",
    "Puente Aranda",
    "Rafael Uribe Uribe",
    "Santa Fe",
    "Martires",
    "Usme"
]
export const barrios_bogota = [
    "Veraguas",
    "El Progreso",
    "Eduardo Santos",
    "El Vergel",
    "Santa Isabel",
    "Santa Isabel Sur",
    "La Pepita",
    "Ricaurte",
    "La Sabana",
    "El Liston",
    "Paloquemao",
    "Quinta Paredes",
    "Gran America",
    "Ciudad Montes",
    "Restrepo",
    "Venecia",
    "La Fraguita",
    "El Jazmin",
    "Modelia",
    "El Salitre",
    "La Soledad",
    "San Luis",
    "Galerias",
    "Chapinero Alto",
    "Chapinero Central",
    "La Cabrera",
    "El Chico",
    "Santa Bibiana",
    "Santa Ana",
    "Cedritos",
    "Lisboa",
    "Santa Barbara",
    "Bella Suiza",
    "Usaquen",
    "El Codito",
    "Suba Rincon",
    "La Campina",
    "Tibabuyes",
    "El Tabor",
    "Rincon de Suba",
    "Santa Helena",
    "Niza",
    "La Floresta",
    "Almendra",
    "Engativa Pueblo",
    "Minuto de Dios",
    "Los Alamos",
    "Boyaca Real",
    "Las Ferias",
    "Normandia",
    "Santa Cecilia",
    "Fontibon Centro",
    "Villemar",
    "Santa Rosita",
    "Bogota Real",
    "Castilla",
    "Marsella",
    "Timiza",
    "Americas Occidental",
    "Patio Bonito",
    "Bosa Centro",
    "El Recreo",
    "San Bernardino",
    "San Jose",
    "El Tintal",
    "Tunal",
    "La Alqueria",
    "Puente Aranda",
    "Prado Veraniego",
    "Los Martires",
    "La Macarena",
    "Egipto",
    "San Cristobal",
    "20 de Julio",
    "El Carmen",
    "Lucero",
    "Juan Rey",
    "Quintanares",
    "El Libertador",
    "La Victoria",
    "El Paraiso",
    "Santa Viviana",
    "Las Cruces",
    "San Bernardo",
    "Eduardo Frey",
    "El Lago",
    "El Polo",
    "La Castellana",
    "Santa Teresita",
    "Los Rosales",
    "El Nogal",
    "Bosque Calderon",
    "San Felipe",
    "Pontevedra",
    "Ciudad Jardin",
    "La Alhambra",
    "San Fernando",
    "San Patricio",
    "Chico Norte",
    "La Calleja",
    "Colina Campestre",
    "Mazuren",
    "Villa del Prado",
    "Torca",
    "El Contador",
    "Bella Vista",
    "El Refugio",
    "Nueva Autopista",
    "La Aurora",
    "Lijaca",
    "San Cristobal Norte",
    "San Cipriano",
    "Atahualpa",
    "El Minuto de Dios",
    "Floridablanca",
    "Santa Maria del Lago",
    "Villa Gladys",
    "Bachue",
    "Garces Navas",
    "Boyaca Real",
    "El Salitre Greco",
    "Morato",
    "Santa Helenita",
    "Villas de Granada",
    "La Riviera",
    "Calle 116",
    "Campin",
    "La Esmeralda",
    "Paraiso",
    "El Mirador",
    "Meissen",
    "Las Margaritas",
    "Santa Marta",
    "El Rosal",
    "Villa Sonia",
    "Tejar",
    "Santa Fe",
    "San Benito",
    "Santa Catalina",
    "Fátima",
    "Molinos del Sur",
    "Cruz Blanca",
    "Carvajal",
    "Venecia",
    "San Eusebio",
    "Nueva Marsella",
    "El Tintal",
    "Ciudad Roma",
    "Villa Alsacia",
    "Palermo",
    "Quinta Ramos",
    "Bolonia",
    "Santiago de las Atalayas",
    "Parque Central Bavaria",
    "La Favorita",
    "Siete de Agosto",
    "San Fernando Occidental",
    "Timiza",
    "El Uval",
    "Vista Hermosa",
    "Casablanca",
    "La Picota",
    "El Rubi"
]